version: "3.2"
services:

  php:
    build: './php/'
    container_name: php
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
  
  nginx:
    build: './nginx/'
    container_name: nginx
    volumes:
      - ./source/:/var/www/html/
    ports:
      - 80:80
    networks:
      - backend

  mariadb:
    container_name: mariadb
    image: mariadb:10.6.4-focal
    environment:
      - MARIADB_DATABASE=opentag
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - dev-local-database-volme:/var/lib/mysql
    tty: true

networks:
  backend:

volumes:
  dev-local-database-volme: