version: "3.2"
services:

  php:
    build: './php/'
    container_name: php
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - ./source/:/var/www/html/
  
  nginx:
    build: './nginx/'
    container_name: nginx
    volumes:
      - ./source/:/var/www/html/
    ports:
      - 80:80
    networks:
      - backend

networks:
  backend:

